config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
   
   devise_scope :user do
     get 'my_page', to: 'users/registrations#my_page'
   end
  
  get "/users/show", to: "devise/sessions#show", as: "user_profile"


  root "welcome#index"
  get "welcome/index"

  # Listing has many offers
  resources :listings do
    resources :offers do
      # Stripe
      resources :charges
    end
  end


  # # listings
  # get "/listings", to: "listings#index", as: "listings"
  # post "/listings", to: "listings#create"
  # get "/listings/new", to: "listings#new", as: "new_listing"
  # get "/listings/:id", to: "listings#show", as: "listing"
  # put "/listings/:id", to: "listings#update"
  # delete "/listings/:id", to: "listing#destroy", as: "delete_listing"
  # get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  patch "/listings/:id/edit", to: "listings#update"
  # delete "/listings", to: "listings#destroy"
  
  # offers
  # get "/offers", to: "offers#index", as: "offers"
  # post "/listings/:id", to: "offers#create"
  # get "/offers", to: "offers#new", as: "new_offer"
  # get "/offers/:id", to: "offers#show", as: "offer"
  # put "/offers/:id", to: "offers#update"
  # delete "/offers/:id", to: "offers#destroy", as: "delete_offer"
  # get "/offers/:id/edit", to: "offers#edit", as: "edit_offer"
  patch "/listings/:id/offers/:id/edit", to: "offers#update"
  get "/offers/your_offers", to: "offers#your_offers", as: "your_offers"
  get "/welcome/your", to: "welcome#your", as: "your_listing"
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy

  def interest_amount
    result = 0
    offers.each do |offer|
      interest = offer.interest / 100
      months = offer.months
      result = amount * interest * months / 12
    end
    # raise
    return result
  end

end

app/controllers/listing_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
  end

  def new

  end
  
  def show
      @listing = Listing.find(params[:id])
  end

  def new
    @listing = current_user.listings.build
  end
  
  def show
      @listing = Listing.find(params[:id])
    end


  def create
    @listing = current_user.listings.build(listing_params)
      
      @listing.save
      redirect_to @listing
    end

    private
    def listing_params
      params.require(:listing).permit(:title, :text)
    end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  protect_from_forgery 
  def index
    @listings = Listing.all
  end

  def your
    @listings = Listing.all
  end

  def new
    @listing = current_user.listings.build
  end
  
  def show
    @listing = Listing.find(params[:id])

  end

  # def edit
  #   @listing = Listing.find(params[:id])
  # end

  def update
    @listing = Listing.find(params[:id])
    
    if @listing.update(listing_params)
      redirect_to @listing
    else
      render 'edit'
    end
  end

  def create
    # @listing = Listing.new(listing_params)
    @listing = current_user.listings.build(listing_params)
    
    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
      
    redirect_to listings_path
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :description, :amount)
    end


end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_listing.html.erb
<div class="container">
  <div class="border2">
    <div class="texta" >
      <div class="listing-title">
        <h2>Title:</h2>
        <p><%= @listing.title %></p>
      </div>
      <div class="listing-amount">
        <h2>Amount:</h2>
        <p>AU<%= number_to_currency(@listing.amount) %></p>
      </div>
      <div class="listing-description">
        <h2>Description:</h2>
        <p><%= @listing.description %></p>
      </div>
      <div class="listing-posted-at">
        <p><strong>Posted at</strong>: <%= @listing.created_at.strftime("%b. %d, %Y") %></p>
        <p><strong>Updated at</strong>: <%= @listing.updated_at.strftime("%b. %d, %Y") %></p>
      </div>

      <% if (user_signed_in? && current_user.id == @listing.user_id && @listing.status == false)%>
        <div class="listing-delete-button">
          <%= link_to "Delete", @listing,
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete ' + @listing.title } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<%= form_for @listing, url: edit_listing_path(@listing), html: {class: "edit-form"},:action => "update" do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :amount %><br>
  <%= f.text_field :amount %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.submit 'Update listing', class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back to #{@listing.title}", listing_path  %>

app/views/listings/index.html.erb
<div class="texta" > <h1>All Loan Requests</h1></div>
<% if can? :create, Listing %>
  <div class="texta"><%= button_to "Create New Listing", new_listing_path, class: 'btn btn-primary', :method => "get" %></div>
<% end %>
<div class="index-page">
  <div class="bookshelf">
    <% @listings.each do |listing| %>
      <div class="book-card bg-light">
        <div class="book-description">
          <h4> <%= listing.title %></h4>
          <p> Description: <%= listing.description %></p>
        </div>
        <div class="index-page-nav-links">
            <button><%= link_to "show", listing %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back', welcome_index_path %> 

app/views/listings/new.html.erb
<% if current_user.user_type == true %>
<div class="texta">
  <h1>Create Your New Request</h1>
</div>
<div class="new-listing-container">
  <%= form_with scope: :listing, url: listings_path, local: true do |form| %>
    <div class="listing-title">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </div>
    <div class="listing-amount">
        <%= form.label :amount %><br>
        <%= form.text_field :amount %>
    </div>
    <div class="listing-description">
        <%= form.label :description %><br>
        <%= form.text_area :description, :cols => 43, :rows => 10 %>
    </div>
    <div class="listing-submit-button">
        <%= form.submit 'Create a new listing', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<% else %>

You do not have permission to view this page

<% end %>

app/views/listings/show.html.erb
<div class="listing-show-page-container">
  <div class="listing-container">
    <% if @listing.status == true %>
      <h1>THIS DEAL HAS BEEEN DONE </h1>
      <%= render 'listing' %>
    <% else %>
      <h1>DEAL STILL THERE </h1>
      <%= render 'listing' %>
    <% end %>
  </div>

  <div class="lenders-offers">
    <h1>OFFERS</h1>
    
    <% if user_signed_in? %>
      <%= render 'offers/accepted_offer' %>
      <%= render 'offers/pending_offer' %>
      <%= render 'offers/rejected_offer' %>
      
      <div class="add-your-new-offer">
        <% if current_user.user_type != true && current_user.id != @listing.user_id && @listing.status == false %>  
          <h2>Add your new offer:</h2>
          <%= render 'offers/form' %>
        <% end %>
      </div>
    <% else %>
      <h2>You can see/add your offers after you <%= link_to 'Sign Up', new_user_registration_path %> / <%= link_to 'Log in', new_user_session_path %>.</h2>
    <% end %> 
  </div>

  <%= link_to 'Back', listings_path %>
</div>