config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
   
   devise_scope :user do
     get 'my_page', to: 'users/registrations#my_page'
   end
  
  get "/users/show", to: "devise/sessions#show", as: "user_profile"


  root "welcome#index"
  get "welcome/index"

  # Listing has many offers
  resources :listings do
    resources :offers do
      # Stripe
      resources :charges
    end
  end


  # # listings
  # get "/listings", to: "listings#index", as: "listings"
  # post "/listings", to: "listings#create"
  # get "/listings/new", to: "listings#new", as: "new_listing"
  # get "/listings/:id", to: "listings#show", as: "listing"
  # put "/listings/:id", to: "listings#update"
  # delete "/listings/:id", to: "listing#destroy", as: "delete_listing"
  # get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  patch "/listings/:id/edit", to: "listings#update"
  # delete "/listings", to: "listings#destroy"
  
  # offers
  # get "/offers", to: "offers#index", as: "offers"
  # post "/listings/:id", to: "offers#create"
  # get "/offers", to: "offers#new", as: "new_offer"
  # get "/offers/:id", to: "offers#show", as: "offer"
  # put "/offers/:id", to: "offers#update"
  # delete "/offers/:id", to: "offers#destroy", as: "delete_offer"
  # get "/offers/:id/edit", to: "offers#edit", as: "edit_offer"
  patch "/listings/:id/offers/:id/edit", to: "offers#update"
  get "/offers/your_offers", to: "offers#your_offers", as: "your_offers"
  get "/welcome/your", to: "welcome#your", as: "your_listing"
  
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_one :charge, dependent: :destroy

  def interest_amount
  @amount = (listing_amount * offer_interest * offer_month / 12).to_i
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # def new
  #   @listing = Listing.find(params[:listing_id])
  #   @offer = @listing.offers.build
  #   respond_with(@offer)
  # end
  def your_offers
    @offers = Offer.all
    @your_offers = []
    
    @offers.each do |offer|
      if offer.user_id == current_user.id
        @your_offers << offer
      end
    end
    return @your_offers
  end

  def go_to_listing_with_your_offer
    
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @offer = @listing.offers.create(offer_params)
    @offer.user_id = current_user.id 
    
    if @offer.save
      flash[:notice] = "Your offer successfully saved!!!"
      redirect_to listing_path(@listing.id)
      @amount = 0
      @listing = Listing.find(params[:listing_id])
      listing_amount = @listing.amount
      @offers = @listing.offers
      @offers.each do |offer|
        offer_interest = offer.interest
        offer_month = offer.months
        @amount = (listing_amount * offer_interest * offer_month / 12).to_i
      end 
    else
      flash[:notice] = "Saving failed"
      redirect_to listing_path(@listing.id)
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
  
    if @offer.update(offer_params)
      redirect_to listing_path(@offer.listing_id)
    else
      render 'edit'
    end
    
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    flash.notice = "Your offer successfully deleted!!!"
    redirect_to listing_path(@offer.listing.id)
  end

  private
    def offer_params
      params.require(:offer).permit(:interest, :months, :description, :status)
    end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_accepted_offer.html.erb
<% @listing.offers.each do |offer| %>
  <% if offer.status == true %>
    <div class="container">
      <div class="border3" >
        <div class="texta">
          <h2>Accepted Offer</h2>
          <div class="offer-id">
            <p><strong>Offer number</strong>: <%= offer.id %></p>
          </div>
          <div class="offer-posted-at">
            <p><strong>Posted at</strong>: <%= offer.created_at.strftime("%b. %d, %Y") %></p>
          </div>
          <div class="offer-updated-at">
            <p><strong>Updated at</strong>: <%= offer.updated_at.strftime("%b. %d, %Y") %></p>
          </div> 
          <div class="offer-lender-name">
            <p>
              <strong>Lender Name:</strong>
              <%= offer.user.name %>
            </p>
          </div>
          <div class="offer-interest">
            <p>
              <strong>Interest rate:</strong>
              <%= offer.interest %> %
            </p>
          </div>
          <div class="offer-term">
            <p>
              <strong>Lending term:</strong>
              <%= offer.months %> months
            </p>
          </div>
          <div class="offer-interest-amount">
            <p>
              <strong>Interest amount:</strong>
              AU<%=  number_to_currency(@listing.amount * (offer.interest/100) * offer.months / 12)%>
            </p>
          </div>
          <div class="offer-description">
            <p>
              <strong>Description:</strong>
              <%= offer.description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/offers/_form.html.erb
<%= form_with(model: [ @listing, @listing.offers.build ], local: true) do |form| %>
  <p>
    <%= form.label :interest_rate %><br>
    <%= form.text_field :interest %> %
  </p>
  <p>
    <%= form.label :lending_term %><br>
    <%= form.text_field :months %> months
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, :cols => 43, :rows => 10 %>
  </p>
  <p>
    <%= form.submit %>
  </p>

  
<% end %>

app/views/offers/_offers.html.erb
<p>
  <strong>Interest:</strong>
  <%= offer.interest %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= offer.description %>
</p>

<p>
  <%= link_to 'Destroy Offer', [offer.listing, offer],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/offers/_pending_offer.html.erb
<% @listing.offers.each do |offer| %>
  <% if offer.status == false && @listing.status == false %>
    <div class="container">
      <div class="border2" >
        <div class="texta" >
          <h2>Pending Offer</h2>
          <div class="offer-id">
            <p><strong>Offer number</strong>: <%= offer.id %></p>
          </div>
          <div class="offer-posted-at">
            <p><strong>Posted at</strong>: <%= offer.created_at.strftime("%b. %d, %Y") %></p>
          </div>
          <div class="offer-updated-at">
            <p><strong>Updated at</strong>: <%= offer.updated_at.strftime("%b. %d, %Y") %></p>
          </div>
          <div class="offer-lender-name">
            <p>
              <strong>Lender Name:</strong>
              <%= offer.user.name %>
            </p>
          </div>
          <div class="offer-interest">
            <p>
              <strong>Interest rate:</strong>
              <%= offer.interest %> %
            </p>
          </div>
          <div class="offer-term">
            <p>
              <strong>Lending term:</strong>
              <%= offer.months %> months
            </p>
          </div>
          <div class="offer-interest-amount">
            <p>
              <strong>Interest amount:</strong>
              AU<%=  number_to_currency(@listing.amount * (offer.interest/100) * offer.months / 12)%>
            </p>
          </div>
          <div class="offer-description">
            <p>
              <strong>Description:</strong>
              <%= offer.description %>
            </p>
          </div>
          <% if current_user.user_type == true && current_user.id == @listing.user_id && @listing.status == false %> 
            <% @amount =  @listing.amount * offer.interest * offer.months / 12 %>
            <%= render "layouts/shared/stripe_form", amount: @amount, offer_id: offer.id %>
          <% end %>
        </div>
        <% if (user_signed_in? && current_user.id == offer.user_id) %>
          <%= link_to 'Edit ', edit_listing_offer_path(@listing, offer.id) %>
        <% end %>
        <% if (user_signed_in? && current_user.id == offer.user_id) %>
          <%= link_to ' Delete', [offer.listing, offer],
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/offers/_rejected_offer.html.erb
<% @listing.offers.each do |offer| %>
  <% if offer.status == false && @listing.status == true %>
    <div class="container">
      <div class="border2">
        <div class="texta" >
          <h2>Rejected Offer</h2>
          <div class="offer-id">
            <p><strong>Offer number</strong>: <%= offer.id %></p>
          </div>
          <div class="offer-posted-at">
            <p><strong>Posted at</strong>: <%= offer.created_at.strftime("%b. %d, %Y") %></p>
          </div>
          <div class="offer-updated-at">
            <p><strong>Updated at</strong>: <%= offer.updated_at.strftime("%b. %d, %Y") %></p>
          </div>
          <div class="offer-lender-name">
            <p>
              <strong>Lender Name:</strong>
              <%= offer.user.name %>
            </p>
          </div>
          <div class="offer-interest">
            <p>
              <strong>Interest rate:</strong>
              <%= offer.interest %> %
            </p>
          </div>
          <div class="offer-term">
            <p>
              <strong>Lending term:</strong>
              <%= offer.months %> months
            </p>
          </div>
          <div class="offer-interest-amount">
            <p>
              <strong>Interest amount:</strong>
              AU<%=  number_to_currency(@listing.amount * (offer.interest/100) * offer.months / 12)%>
            </p>
          </div>
          <div class="offer-description">
            <p>
              <strong>Description:</strong>
              <%= offer.description %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% if current_user.user_type == true && current_user.id == @listing.user_id && @listing.status == false %> 
      <% @amount =  @listing.amount * offer.interest * offer.months / 12 %>
      <%= render "layouts/shared/stripe_form", amount: @amount, offer_id: offer.id %>
    <% end %>
  <% end %>
<% end %>

app/views/offers/edit.html.erb
<% if current_user.user_type == false %>
  <div class="texta">
    <h1>Update Your Offer</h1>
  </div>
  <div class="edit-offer-container">

  <%= form_for @offer, url: edit_listing_offer_path(@offer.listing_id), html: {class: "edit-form"},:action => "update" do |form| %>
    <div class="offer-interest">
      <%= form.label :interest_rate %>
      <%= form.text_field :interest %>
    </div>
    <div class="offer-months">
      <%= form.label :lending_term %>
      <%= form.text_field :months %>
    </div>
    <div class="offer-description">
      <%= form.label :description %>
      <%= form.text_area :description, :cols => 43, :rows => 10 %>
    </div>
    <div class="offer-submit-button">
      <%= form.submit 'Update offer', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to "Back", :back  %>

<% else %>

<h1>You do not have permission to view this page!!</h1>

<% end %>

app/views/offers/new.html.erb
<%= form_with scope: :listing, url: listings_path, local: true do |form| %>
  <p>
    <%= form.label :interest %><br>
    <%= form.text_field :description %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'To Listings', listings_path %>

app/views/offers/your_offers.html.erb
<div class="texta" > <h1>My Offers</h1></div>
<% if user_signed_in? %>
  <% if current_user.user_type == false %>
    <div class="index-page">
      <div class="bookshelf">
        <% @your_offers.each do |offer| %>
          <div class="book-card bg-light">
            <div class="book-description">
              <p> Offer # <%= offer.id %></p>
              <% if offer.listing.status == false %>
                <h3>Pending</h3>
              <% elsif offer.status == true%>
                <h3>Accepted</h3>
              <% else %>
                <h3>Rejected</h3>
              <% end %>
              <p> Offered date: <%= offer.created_at.strftime("%b. %d, %Y") %></p>
              <p> Interest rate: <%= offer.interest %> %</p>
              <p> Description: <%= offer.description %></p>
            </div>
            <%= link_to 'Go to the request', listing_path(offer.listing) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>